### ISSUE TITLE
Compiling Text.Bibtex.ListPapers fails on Mac OSX

### ISSUE THREAD

**Issue by liyuanfang** [robstewart57/dblp2bibtex#2]
I was trying to install dblp2bibtex but encountered the following problem: 

$ cabal install
Resolving dependencies...
Configuring dblp2bibtex-0.0.3...
Building dblp2bibtex-0.0.3...
Preprocessing library dblp2bibtex-0.0.3...
[1 of 3] Compiling Text.Bibtex.ListPapers ( Text/Bibtex/ListPapers.hs, dist/build/Text/Bibtex/ListPapers.o )

Text/Bibtex/ListPapers.hs:21:24:
    Couldn't match expected type `T.Text' with actual type `String'
    In the first argument of `iriRef', namely `authorURI'
    In the expression: iriRef authorURI
    In an equation for `author': author = iriRef authorURI
cabal: Error: some packages failed to install:
dblp2bibtex-0.0.3 failed during the building phase. The exception was:
ExitFailure 1

Note that haskell platform and cabal are installed via mac ports. Thank you!

**Comment by billhowe** [comment]
I'm years late, but I get the same error.  My GHC version on OSX is "The Glorious Glasgow Haskell Compilation System, version 7.10.3"

Previously attempted on "The Glorious Glasgow Haskell Compilation System, version 7.8.3" with the same results.

**Comment by robstewart57** [comment]
@liyuanfang @billhowe The good is that I've fixed this compilation error: https://github.com/robstewart57/dblp2bibtex/commit/e34911aa39f37a527ddd7493d90a6ac430536499 .

The less good news is that this software depended on a web service that is no longer live. I've updated the README.md to document this: https://github.com/robstewart57/dblp2bibtex/commit/b094daa1dc83fa5e19032102970070e90e980fb8
